version: '3.8'

services:
  m1-extraction:
    build:
      context: ./AI-Microservices/m1_extraction_service
    container_name: ai_m1_extraction
    ports:
      - "8001:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
    
  skill-normalization:
    build:
      context: ./AI-Microservices/skill_normalization_service
    container_name: ai_skill_normalization
    ports:
      - "8002:8003"
    restart: unless-stopped

  gap-engine:
    build:
      context: ./AI-Microservices/gap-engin-service
    container_name: ai_gap_engine
    ports:
      - "8004:8003"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
